[book]
authors = ["MaximilianHertenstein"]
language = "de"

[output.html]
theme = "src/book_theme"
additional-css = [ "src/book_theme/additional.css" ]
additional-js = [ "src/book_theme/runner.js" ]

[preprocessor.quiz]
optional = true