[[questions]]
type = "MultipleChoice"
prompt.prompt = "Welchen Index hat der erste Buchstabe eines Strings?"
prompt.distractors = [
  "1",
  "-1",
  "Es kommt auf die Länge des Strings an."
]
answer.answer = "0, weil die Indizierung in Python bei 0 beginnt."
context = "Die Indizierung von Strings beginnt immer bei 0, nicht bei 1."
id = "0b1c2d3e-2e3d-4a3a-9e2a-9d1f6b7a3c21"
