[[questions]]
type = "MultipleChoice"
prompt.prompt = "Was ergibt `8 / 2` in Python?"
prompt.distractors = [
  "4",
  "8",
  "2"
]
answer.answer = "4.0"
context = "Bei Divisionen liefert Python oft eine Zahl mit Komma. `8 / 2` ergibt `4.0`, nicht nur `4`."
id = "58b9569e-8f8d-4c75-9b27-6679e51f30db"
