[[questions]]
type = "MultipleChoice"
prompt.prompt = "Welches Ergebnis liefert `1 + 2 * 5`?"
prompt.distractors = [
  "15",
  "7",
  "30"
]
answer.answer = "11"
context = "Die Multiplikation hat in Python Vorrang vor der Addition."
id = "e46ba554-71f9-44ea-aec8-0aa5d74c4e7f"
